#:schema node_modules/wrangler/config-schema.json
name = "talos"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

# ==========================================
# Environment: Staging
# ==========================================
[env.staging]
name = "app-staging"

[env.staging.vars]
NODE_ENV = "staging"

# ==========================================
# Environment: Production
# ==========================================
[env.production]
name = "talos"

[env.production.vars]
NODE_ENV = "production"
