blank_issues_enabled: false
contact_links:
  - name: upstream platform issues
    url: https://github.com/Talomia/Talos/issues/new/choose
    about: Report upstream platform issues
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Talos users.
